name: Deploy Azure Function App

on:
  push:
    branches:
      - create-ci-cd-pipeline

env:
  AZURE_FUNCTIONAPP_LOCATION: 'francecentral'
  AZURE_FUNCTIONAPP_NAME: 'tobiasodionia'
  AZURE_FUNCTIONAPP_VERSION: '4'
  AZURE_FUNCTIONAPP_STORAGE: 'tobiasodioniastorage'
  AZURE_FUNCTIONAPP_STORAGE_SKU: 'Standard_LRS'
  AZURE_RESOURCE_GROUP: 'tobiasodionia'

  DOTNET_VERSION: '6.0'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/build-artifacts'
  BUILD_PACKAGE_NAME: 'tobiasodionia.zip'

  GPT_API_BASE_URL: 'https://api.openai.com'
  GPT_API_COMPLETION_ENDPOINT: '/v1/completions'
  SMTP_HOST: 'smtp.gmail.com'
  SMTP_PORT: '587'
      
jobs:
  set-up-function-app-on-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Function App exists
        id: check_function_app
        run: |
          # Check if the function app exists
          az functionapp show \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          
      - name: Create Azure Function
        if: steps.check_function_app.outputs.result != 'null'
        run: |
          # Function App already exist
          echo "Function App already set up on cloud"
          
      - name: Create Azure Function
        if: steps.check_function_app.outputs.result == 'null'
        run: |
          # Create a resource group
          echo "Creating $resourceGroup in "$location"..."
          az group create \
          --name ${{ env.AZURE_RESOURCE_GROUP }} \
          --location ${{ env.AZURE_FUNCTIONAPP_LOCATION }} \
          
          # Create an Azure storage account in the resource group.
          echo "Creating $storage"
          az storage account create \
          --name ${{env.AZURE_FUNCTIONAPP_STORAGE}} \
          --location ${{ env.AZURE_FUNCTIONAPP_LOCATION }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --sku ${{ env.AZURE_FUNCTIONAPP_STORAGE_SKU }} \
          --allow-blob-public-access true \
          
          # Create a serverless function app in the resource group.
          echo "Creating $functionApp"
          az functionapp create \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --storage-account ${{env.AZURE_FUNCTIONAPP_STORAGE}} \
          --consumption-plan-location ${{ env.AZURE_FUNCTIONAPP_LOCATION }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --functions-version ${{ env.AZURE_FUNCTIONAPP_VERSION }} \

  #######################################################################################################
  update-function-app-configuration:
    runs-on: ubuntu-latest

    needs: [set-up-function-app-on-cloud]

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Retrieve Configurations
        id: retrieve-configs
        run: |
          # Retrieve existing configurations
          CONFIGS=$(az functionapp config appsettings list --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --output json)
          echo "::set-output name=configs::$CONFIGS"
  
      - name: Append New Configurations
        id: append-configs
        run: |
          NEW_CONFIG='[
            {
              "name" : "GPT_API_KEY",
              "slotSetting" : false,
              "value": "${{secrets.GPT_API_KEY}}"
            },
            {
              "name" :"EMAIL_ACCOUNT",
              "slotSetting" : false,
              "value":"${{secrets.EMAIL_ACCOUNT}}"
            },
            {
              "name" :"EMAIL_PASSWORD",
              "slotSetting" : false,
              "value":"${{secrets.EMAIL_PASSWORD}}" 
            },
            {
              "name" :"GPT_API_BASE_URL",
              "slotSetting" : false,
              "value":"${{env.GPT_API_BASE_URL}}"
            },
            {
                "name" :"GPT_API_COMPLETION_ENDPOINT",
                "slotSetting" : false,
                "value":"${{env.GPT_API_COMPLETION_ENDPOINT}}"
            },
            {
                "name" :"SMTP_HOST", 
                "slotSetting" : false,
                "value":"${{env.SMTP_HOST}}"
            },
            {
                "SMTP_PORT": 
                "slotSetting" : false,
                "value":"${{env.SMTP_PORT}}"
            }]'
            
          # Append new configurations (replace with your logic)
          ALL_CONFIGS=$(jq -s '.[0] + .[1]' <<< "${{ steps.retrieve-configs.outputs.configs }} $NEW_CONFIG")
          echo "::set-output name=all_configs::$ALL_CONFIGS"
  
      - name: Update Configurations on Azure
        run: |
          # Update configurations on Azure
          az functionapp config appsettings set --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --settings "$ALL_CONFIGS"
  

  #######################################################################################################
  build-publish-az-function:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      
      - name: Build and Publish Azure Function
        run: |
            dotnet build
            dotnet publish -o bin/publish
            mkdir ${{ env.BUILD_OUTPUT_PATH }}
            cd ${{ github.workspace }}/bin/publish
            zip -r ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }} .

      # Upload the code artifact, this will be used later
      - name: 'Package Azure Function release build'
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}
          if-no-files-found: error

  #######################################################################################################
  deploy-az-function:
    runs-on: ubuntu-latest
      
    needs: [update-function-app-configuration, build-publish-az-function]
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Create output directory'
        shell: bash
        run: |
           mkdir ${{ env.BUILD_OUTPUT_PATH }}

       # Fetch published code
      - name: 'Download Azure function release build'
        uses: actions/download-artifact@v2
        with:
          name: build_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}
      
      - name: Run Final Step
        run: |
          az functionapp deployment source config-zip --resource-group tobiasodionia --name tobiasodionia --src ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }}
