name: Deploy Azure Function App

on:
  push:
    branches:
      - create-ci-cd-pipeline
      
jobs:
  set-up-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Function
        run: |
          # Function app and storage account names must be unique.
          # Variable block
          location="francecentral"
          resourceGroup="tobiasodionia"
          storage="tobiasodioniastorage"
          functionApp="tobiasodionia"
          skuStorage="Standard_LRS"
          functionsVersion="4"
          
          # Create a resource group
          echo "Creating $resourceGroup in "$location"..."
          az group create --name $resourceGroup --location "$location" --tags $tag
          
          # Create an Azure storage account in the resource group.
          echo "Creating $storage"
          az storage account create --name $storage --location "$location" --resource-group $resourceGroup --sku $skuStorage
          
          # Create a serverless function app in the resource group.
          echo "Creating $functionApp"
          az functionapp create --name $functionApp --storage-account $storage --consumption-plan-location "$location" --resource-group $resourceGroup --functions-version $functionsVersion

  #######################################################################################################
  build-publish-az-function:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      
      - name: Build and Publish Azure Function
        run: |
            dotnet build
            dotnet publish -o bin/publish
            mkdir ${{ github.workspace }}/build-artifacts
            cd ${{ github.workspace }}/bin/publish
            zip -r ${{ github.workspace }}/build-artifacts/wwwroot.zip .

      # Upload the code artifact, this will be used later
      - name: 'Package Azure Function release build'
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}/build-artifacts
          if-no-files-found: error

  #######################################################################################################
  deploy-az-function:
    runs-on: ubuntu-latest
      
    needs: [set-up-cloud, build-publish-az-function]
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run Final Step
        run: |
          az functionapp deployment source config-zip --resource-group tobiasodionia --name tobiasodionia --src ${{ github.workspace }}/build-artifacts/wwwroot.zip
